feat(VENLY-2762): add read() method in ContractService
ArkaneNetwork/blockchain-providers pull request #105
Opened 2021-09-15 14:41 UTC by aleksanderndoci

2021-09-15 14:57 UTC, alpa-coder requested changes

2021-09-15 14:57 UTC, alpa-coder commented on provider-api/src/main/java/network/arkane/provider/contract/ContractService.java
> +    }
you can keep the existing call callFunction, but change the return type for it. so remove the read function and refactor the callFunction to return List<Object>

2021-09-15 14:57 UTC, alpa-coder commented on provider-evm/src/main/java/network/arkane/provider/contract/EvmContractService.java
> +    public List<Object> read(ContractCall contractCall) {
As above, refactor callFunction call

2021-09-16 07:33 UTC, alpa-coder requested changes

2021-09-16 07:33 UTC, alpa-coder commented on provider-evm/src/main/java/network/arkane/provider/contract/EvmContractService.java
> +    public List<Object> callFunction(ContractCall contractCall) {
should have covered it as well in previous review, but maybe interesting to have some kind of object that holds the data (type/value) where some generics are used. For example creating an object called ContractCallResultParam which is the generic supertype, create subclasses like: NumericContractCallResult, ...

We can disccuss this on slack

2021-09-17 07:39 UTC, alpa-coder requested changes

2021-09-17 07:39 UTC, alpa-coder commented on provider-evm/src/main/java/network/arkane/provider/contract/ContractCallResultTypeFactory.java
> +
this mapping will maybe not be sufficient, can you check AbiTypesFactory, if you use it like over there, all types should be mapped correctly

2021-09-17 09:45 UTC, alpa-coder requested changes

2021-09-17 09:45 UTC, alpa-coder commented on provider-evm/src/main/java/network/arkane/provider/contract/ContractCallResultTypeFactory.java
> +        switch (type.hashCode()) {
I would create a public method to get this value in/from AbiTypesFactory, you don't want to have this logic twice, it is already super ugly :D

2021-09-17 09:50 UTC, aleksanderndoci commented on provider-evm/src/main/java/network/arkane/provider/contract/ContractCallResultTypeFactory.java
> +        switch (type.hashCode()) {
You mean the value for var2 ?

2021-09-17 11:37 UTC, alpa-coder approved these changes

2021-09-17 11:37 UTC, merged