refactor(VENLY-2793): remove arkane-business module
ArkaneNetwork/blockchain-providers pull request #110
Opened 2021-10-01 09:53 UTC by aleksanderndoci

2021-10-04 11:42 UTC, nico-ptrs requested changes

2021-10-04 11:42 UTC, nico-ptrs commented on provider-evm/src/main/java/network/arkane/provider/nonfungible/BlockscoutNonFungibleStrategy.java
> +        //        }
Is there a good reason to put this in comments? If it's not used anymore, just delete it...

2021-10-04 12:21 UTC, aleksanderndoci commented on provider-evm/src/main/java/network/arkane/provider/nonfungible/BlockscoutNonFungibleStrategy.java
> +        //        }
Nope, just leftover that slipped my eye during refactor. Good catch, thanks :)

2021-10-05 12:35 UTC, alpa-coder approved these changes

2021-10-06 13:51 UTC, nico-ptrs approved these changes

2021-10-06 13:52 UTC, merged