Hotfix 0.37.4
ArkaneNetwork/blockchain-providers pull request #122
Opened 2021-12-09 16:40 UTC by nico-ptrs

2021-12-09 18:10 UTC, alpa-coder requested changes

2021-12-09 18:10 UTC, alpa-coder commented on provider-evm/src/main/java/network/arkane/provider/balance/EvmCovalentBalanceStrategy.java
> +            return super.getTokenBalances(walletAddress, tokenAddresses);
maybe add a guard if tokenaddress list  is empty you return them all...?

2021-12-09 18:10 UTC, alpa-coder commented on provider-vechain/src/main/java/network/arkane/provider/balance/VechainBalanceGateway.java
> +                                                         .collect(Collectors.toList());
maybe do this in parallel (also for all the other tokeninfos that are fetched like this)..?

2021-12-09 19:34 UTC, closed without merging

2021-12-10 08:47 UTC, nico-ptrs commented on provider-evm/src/main/java/network/arkane/provider/balance/EvmAzraelBalanceStrategy.java
> +        final List<String> lowerCaseTokenAddresses = tokenAddresses.stream().map(String::toLowerCase).collect(Collectors.toList());
done

2021-12-10 09:04 UTC, nico-ptrs commented on provider-evm/src/main/java/network/arkane/provider/balance/EvmCovalentBalanceStrategy.java
> +            return super.getTokenBalances(walletAddress, tokenAddresses);
Done

2021-12-10 10:30 UTC, nico-ptrs commented on provider-vechain/src/main/java/network/arkane/provider/balance/VechainBalanceGateway.java
> +                                                         .collect(Collectors.toList());
Done