feat(VENLY-3756) IMX - Get ERC20 Token balance
ArkaneNetwork/blockchain-providers pull request #160
Opened 2022-07-08 12:12 UTC by maciejwitwicki

2022-07-11 15:42 UTC, alpa-coder requested changes

2022-07-11 15:42 UTC, alpa-coder commented on provider-api/src/main/java/network/arkane/provider/balance/BlockchainProviderBalanceGateway.java
> +    private static final String TOKEN_BALANCES_URL = "/api/wallets/balances/{walletAddress}";
For me this seems a bit of a weird restful endpoint, I would expect more something like "/api/wallets/{walletAddress}/token-balances/"

2022-07-12 06:41 UTC, maciejwitwicki commented on provider-api/src/main/java/network/arkane/provider/balance/BlockchainProviderBalanceGateway.java
> +    private static final String TOKEN_BALANCES_URL = "/api/wallets/balances/{walletAddress}";
Fixed. Corresponding PR in the imx-blockchain-provider: [https://github.com/ArkaneNetwork/imx-blockchain-provider/pull/32
](https://github.com/ArkaneNetwork/imx-blockchain-provider/pull/32
)

2022-07-14 14:44 UTC, alpa-coder approved these changes

2022-07-15 06:37 UTC, merged