bug(VENLY-3825) - change HEDERA not implemented error message
ArkaneNetwork/blockchain-providers pull request #164
Opened 2022-07-21 11:33 UTC by ZhamakochyanErik

2022-07-21 12:25 UTC, aleksanderndoci requested changes

2022-07-21 12:25 UTC, aleksanderndoci commented on provider-hedera/src/main/java/network/arkane/provider/hedera/blockchain/HederaBlockchainInfoService.java
> +        throw new NotImplementedException(String.format("Feature not implemented for %s, because %s doesn't have blockNumber", type().name(), type().name()));
As previously discussed in Slack I think it's better if instead of throwing errors and having the API return an error response, just return the data we have for each enabled chain on the wallet

2022-07-21 12:25 UTC, aleksanderndoci commented on provider-hedera/src/main/java/network/arkane/provider/hedera/blockchain/HederaBlockchainInfoService.java
> +        throw new NotImplementedException(String.format("Feature not implemented for %s, because %s doesn't have blockNumber", type().name(), type().name()));
(will talk with Pavlo to change the ticket desc as well)

2022-07-21 12:27 UTC, maciejwitwicki commented on provider-hedera/src/main/java/network/arkane/provider/hedera/blockchain/HederaBlockchainInfoService.java
> +        throw new NotImplementedException(String.format("Feature not implemented for %s, because %s doesn't have blockNumber", type().name(), type().name()));
Not relevant after the Aleksander's comment, but in future to reuse an argument to String.format you can use `%1$s`: 
```
String.format("%1$s FOO %1$s %1$s", "test")
```

2022-07-21 12:51 UTC, ZhamakochyanErik commented on provider-hedera/src/main/java/network/arkane/provider/hedera/blockchain/HederaBlockchainInfoService.java
> +        throw new NotImplementedException(String.format("Feature not implemented for %s, because %s doesn't have blockNumber", type().name(), type().name()));
sorry I didn't get 
for HEDERA getBlockNumber what should we return null or 0 ?

2022-07-21 13:01 UTC, aleksanderndoci commented on provider-hedera/src/main/java/network/arkane/provider/hedera/blockchain/HederaBlockchainInfoService.java
> +        throw new NotImplementedException(String.format("Feature not implemented for %s, because %s doesn't have blockNumber", type().name(), type().name()));
Let's continue the discussion over a call in slack

2022-08-01 13:56 UTC, aleksanderndoci approved these changes

2022-08-02 10:49 UTC, merged