bug(VENLY-3890) - add ImxTokenDiscoveryService
ArkaneNetwork/blockchain-providers pull request #167
Opened 2022-07-28 20:03 UTC by ZhamakochyanErik

2022-08-01 13:58 UTC, aleksanderndoci commented on provider-imx/src/main/java/io/venly/provider/imx/NativeImxTokenDiscoveryService.java
> +public class NativeImxTokenDiscoveryService implements NativeTokenDiscoveryService {
Name this ImxTokenDiscorveryService

2022-08-01 14:02 UTC, aleksanderndoci requested changes

2022-08-01 14:02 UTC, aleksanderndoci commented on provider-imx/src/main/java/io/venly/provider/imx/NativeImxTokenDiscoveryService.java
> +        ImxTokenInfoDto imxTokenInfoDto = blockchainProviderGatewayClient.get("/api/tokens/%s".formatted(tokenAddress), ImxTokenInfoDto.class);
change this to `blockchainProviderGatewayClient.get("/api/tokens/{tokenAddress}", ImxTokenInfoDto.class, tokenAddress)`

2022-08-01 14:02 UTC, aleksanderndoci commented on provider-imx/src/main/java/io/venly/provider/imx/ImxAutoConfiguration.java
> +    NativeImxTokenDiscoveryService nativeImxTokenDiscoveryService(BlockchainProviderGatewayClient blockchainProviderGatewayClient) {
This can be final

2022-08-02 10:23 UTC, aleksanderndoci requested changes

2022-08-02 10:23 UTC, aleksanderndoci commented on provider-imx/src/main/java/io/venly/provider/imx/dto/ImxTokenInfoDto.java
> +    private String decimals;
Shouldn't this be integer/long ?

2022-08-02 10:30 UTC, ZhamakochyanErik commented on provider-imx/src/main/java/io/venly/provider/imx/dto/ImxTokenInfoDto.java
> +    private String decimals;
from ImxGateway getTokenInfo() method returns String 
I just cast in the blockchain-providers after getting from Imx

2022-08-03 10:29 UTC, aleksanderndoci approved these changes

2022-08-03 13:31 UTC, merged