feat(ARKANE-2367): determine correct animationType for unknown types
ArkaneNetwork/blockchain-providers pull request #97
Opened 2021-05-06 14:45 UTC by nico-ptrs

[ARKANE-2367]

2021-05-06 15:05 UTC, alpa-coder requested changes

2021-05-06 15:05 UTC, alpa-coder commented on provider-evm/src/main/java/network/arkane/provider/nonfungible/NonFungibleMetaData.java
> +                                          .orElse(String.valueOf(animationUrls.get(0).getValue())));
shouldn't you parse the fallback as well?

2021-05-06 15:37 UTC, nico-ptrs commented on provider-evm/src/main/java/network/arkane/provider/nonfungible/NonFungibleMetaData.java
> +                                          .orElse(String.valueOf(animationUrls.get(0).getValue())));
It fetches the TypeValues from `getAnimationUrls()`, so they should be mapped correctly. The only I'm wondering is why it is explicitly filtering on `tv.getType().equalsIgnoreCase("unknown")`. Because of this, probably not a lot will come through anymore.

2021-05-07 08:04 UTC, alpa-coder requested changes

2021-05-07 08:04 UTC, alpa-coder commented on provider-evm/src/main/java/network/arkane/provider/nonfungible/NonFungibleMetaData.java
> +                                          .orElse(String.valueOf(animationUrls.get(0).getValue())));
Take as animationUrl:

1. If video is present : the first video
2. if no video is present: the first audio
3. if no audio is present: the first image
4. if none of the above: the first one in the list

2021-05-07 09:25 UTC, nico-ptrs commented on provider-evm/src/main/java/network/arkane/provider/nonfungible/NonFungibleMetaData.java
> +                                          .orElse(String.valueOf(animationUrls.get(0).getValue())));
AnimationTypeComparator.java has been created to be able to determine the highest priority, which is then returned

2021-05-07 09:30 UTC, alpa-coder commented on provider-evm/src/main/java/network/arkane/provider/nonfungible/animationtype/AnimationTypeComparator.java
> +        return Integer.compare(TYPES_ORDER.indexOf(tv1.getType()), TYPES_ORDER.indexOf(tv2.getType()));
what happens when type is unknown?

2021-05-07 09:32 UTC, nico-ptrs commented on provider-evm/src/main/java/network/arkane/provider/nonfungible/animationtype/AnimationTypeComparator.java
> +        return Integer.compare(TYPES_ORDER.indexOf(tv1.getType()), TYPES_ORDER.indexOf(tv2.getType()));
if type is unknown indexof = -1

2021-05-07 09:33 UTC, alpa-coder commented on provider-evm/src/main/java/network/arkane/provider/nonfungible/animationtype/AnimationTypeComparator.java
> +        return Integer.compare(TYPES_ORDER.indexOf(tv1.getType()), TYPES_ORDER.indexOf(tv2.getType()));
is that the desired behaviour?

2021-05-07 09:34 UTC, nico-ptrs commented on provider-evm/src/main/java/network/arkane/provider/nonfungible/animationtype/AnimationTypeComparator.java
> +        return Integer.compare(TYPES_ORDER.indexOf(tv1.getType()), TYPES_ORDER.indexOf(tv2.getType()));
yes, see AnimationTypeComparatorTest.java

2021-05-07 09:36 UTC, alpa-coder requested changes

2021-05-07 09:36 UTC, alpa-coder commented on provider-evm/src/main/java/network/arkane/provider/nonfungible/animationtype/AnimationTypeComparator.java
> +        return Integer.compare(TYPES_ORDER.indexOf(tv1.getType()), TYPES_ORDER.indexOf(tv2.getType()));
I have a feeling this comparator does what it needs to do when working together with the other logic you are trying to achieve. But from a comparator point of view does not make sense.

When I blindly use this comparator Collections.sort(typeValues, comparator), I would expect my list to be sorted video -> audio -> image -> ...

which is not the case, in fact I will get the least interesting ones first

2021-05-07 09:51 UTC, nico-ptrs commented on provider-evm/src/main/java/network/arkane/provider/nonfungible/animationtype/AnimationTypeComparator.java
> +        return Integer.compare(TYPES_ORDER.indexOf(tv1.getType()), TYPES_ORDER.indexOf(tv2.getType()));
good point, I reversed it

2021-05-07 10:03 UTC, alpa-coder approved these changes

2021-05-07 10:41 UTC, merged